In [1]:
import pandas as pd
from epiweeks import Week
# from datetime import datetime, date
from bulletin.data.notifica import Notifica
from bulletin import __file__ as __root__
from bulletin.metabase.request import download_metabase

In [2]:
notifica = Notifica()

In [3]:
notifica.download_todas_notificacoes()

Requesting classificacao_final IS NULL AND nt.metodo <> '' AND nt.metodo <> '3' AND nt.metodo IS NOT NULL AND nt.excluir_ficha = '2' AND nt.uf_residencia = '41' AND nt.uf_unidade_notifica = '41' AND (nt.status_notificacao = '1' OR nt.status_notificacao = '2')
Success code 200
Saving in input\queries_exames\null.csv
Download finish, time elapsed: 0:00:00.595040
downloaded shape (17, 4)

Requesting classificacao_final = 0 AND nt.metodo <> '' AND nt.metodo <> '3' AND nt.metodo IS NOT NULL AND nt.excluir_ficha = '2' AND nt.uf_residencia = '41' AND nt.uf_unidade_notifica = '41' AND (nt.status_notificacao = '1' OR nt.status_notificacao = '2')
Success code 200
Saving in input\queries_exames\0.csv
Download finish, time elapsed: 0:00:00.061202
downloaded shape (12, 4)

Requesting classificacao_final = 1 AND nt.metodo <> '' AND nt.metodo <> '3' AND nt.metodo IS NOT NULL AND nt.excluir_ficha = '2' AND nt.uf_residencia = '41' AND nt.uf_unidade_notifica = '41' AND (nt.status_notificacao = '1' OR nt.status_notificacao = '2')
Success code 200
Saving in input\queries_exames\1.csv
Download finish, time elapsed: 0:00:26.867492
downloaded shape (343499, 4)

Requesting classificacao_final = 2 AND nt.metodo <> '' AND nt.metodo <> '3' AND nt.metodo IS NOT NULL AND nt.excluir_ficha = '2' AND nt.uf_residencia = '41' AND nt.uf_unidade_notifica = '41' AND (nt.status_notificacao = '1' OR nt.status_notificacao = '2')
Success code 200
Saving in input\queries_exames\2.csv
Download finish, time elapsed: 0:00:43.815541
downloaded shape (825042, 4)

Requesting classificacao_final = 3 AND nt.metodo <> '' AND nt.metodo <> '3' AND nt.metodo IS NOT NULL AND nt.excluir_ficha = '2' AND nt.uf_residencia = '41' AND nt.uf_unidade_notifica = '41' AND (nt.status_notificacao = '1' OR nt.status_notificacao = '2')
Success code 200
Saving in input\queries_exames\3.csv
Download finish, time elapsed: 0:00:41.077840
downloaded shape (713873, 4)

Requesting classificacao_final = 5 AND nt.metodo <> '' AND nt.metodo <> '3' AND nt.metodo IS NOT NULL AND nt.excluir_ficha = '2' AND nt.uf_residencia = '41' AND nt.uf_unidade_notifica = '41' AND (nt.status_notificacao = '1' OR nt.status_notificacao = '2')
Success code 200
Saving in input\queries_exames\5.csv
Download finish, time elapsed: 0:00:02.974157
downloaded shape (3804, 4)

In [4]:
notifica.read_todas_notificacoes()

In [5]:
todos_exames = notifica.get_casos()

In [17]:
#todos_exames.loc[~todos_exames['data_notificacao'].isnull(), 'ano'] = todos_exames['data_notificacao'].loc[~todos_exames['data_notificacao'].isnull()].apply(lambda x: Week.fromdate(x).year)
#todos_exames.loc[~todos_exames['data_notificacao'].isnull(), 'se'] = todos_exames['data_notificacao'].loc[~todos_exames['data_notificacao'].isnull()].apply(lambda x: Week.fromdate(x).week)
todos_exames = todos_exames.loc[~todos_exames['ibge_unidade_notifica'].isnull()]
todos_exames = todos_exames.loc[~todos_exames['data_notificacao'].isnull()]
todos_exames = todos_exames.loc[todos_exames['data_notificacao'] >= '2021-02-26']
todos_exames['se'] = todos_exames['data_notificacao'].apply(lambda x: Week.fromdate(x))

In [18]:
#tabela = todos_exames.groupby(['se','classificacao_final'])[['metodo']].count().unstack()
tabela = todos_exames.groupby(['data_notificacao','classificacao_final'])[['metodo']].count().unstack()

In [20]:
tabela = tabela.droplevel(0, axis=1)

In [33]:
tabela['exames'] = tabela.sum(1)
tabela['positividade']= tabela[2].div(tabela['exames'])

In [ ]:
# for row in tabela.index.values:
#     if row.year < 2020:
#         tabela = tabela.drop(row)

In [ ]:
# tabela = tabela[[2, 3, 1, 5, 0]]

In [ ]:
# tabela.loc[tabela[5].isnull(), 5] = 0
# tabela.loc[tabela[0].isnull(), 0] = 0
# tabela[5] = tabela[5].add(tabela[0])
# tabela = tabela.drop(0, axis=1)

In [35]:
tabela.to_excel('output/exames_notifica.xlsx')

In [34]:
tabela

classificacao_final  0.0     1.0     2.0     3.0   exames  positividade
data_notificacao
2021-02-26           NaN  1779.0  5741.0  4390.0  11910.0      0.482032
2021-02-27           NaN  1061.0  3016.0  1631.0   5708.0      0.528381
2021-02-28           NaN   460.0  1903.0   987.0   3350.0      0.568060
2021-03-01           1.0  2005.0  7195.0  5020.0  14221.0      0.505942
2021-03-02           NaN  2115.0  6901.0  4968.0  13984.0      0.493493
2021-03-03           NaN  1674.0  5951.0  4305.0  11930.0      0.498826
2021-03-04           NaN  2220.0  6262.0  4251.0  12733.0      0.491793
2021-03-05           NaN  1930.0  5691.0  3780.0  11401.0      0.499167
2021-03-06           NaN  1429.0  2768.0  1323.0   5520.0      0.501449
2021-03-07           NaN   473.0  1870.0   958.0   3301.0      0.566495
2021-03-08           NaN  1925.0  7236.0  4635.0  13796.0      0.524500
2021-03-09           NaN  2143.0  6606.0  4067.0  12816.0      0.515449
2021-03-10           NaN  2304.0  5813.0  4003.0  12120.0      0.479620
2021-03-11           NaN  1984.0  5522.0  4306.0  11812.0      0.467491
2021-03-12           NaN  2333.0  5649.0  4361.0  12343.0      0.457668
2021-03-13           NaN  1786.0  3388.0  2049.0   7223.0      0.469057
2021-03-14           NaN   793.0  1984.0  1307.0   4084.0      0.485798
2021-03-15           NaN  2549.0  6608.0  4780.0  13937.0      0.474134
2021-03-16           NaN  2667.0  5816.0  4394.0  12877.0      0.451658
2021-03-17           NaN  2370.0  5539.0  4082.0  11991.0      0.461930
2021-03-18           NaN  2472.0  5217.0  4178.0  11867.0      0.439622
2021-03-19           NaN  3088.0  5049.0  3950.0  12087.0      0.417722
2021-03-20           NaN  1514.0  2443.0  1302.0   5259.0      0.464537
2021-03-21           NaN   981.0  1418.0   738.0   3137.0      0.452024
2021-03-22           NaN  2682.0  6448.0  4678.0  13808.0      0.466976
2021-03-23           NaN  2879.0  5359.0  4246.0  12484.0      0.429269
2021-03-24           NaN  2463.0  4756.0  3894.0  11113.0      0.427967
2021-03-25           NaN  2782.0  3969.0  3363.0  10114.0      0.392426
2021-03-26           NaN  2859.0  3842.0  3168.0   9869.0      0.389300
2021-03-27           NaN  1449.0  2004.0  1286.0   4739.0      0.422874
2021-03-28           NaN   759.0  1326.0   644.0   2729.0      0.485892
2021-03-29           NaN  2201.0  4331.0  3768.0  10300.0      0.420485
2021-03-30           NaN  2648.0  3392.0  3209.0   9249.0      0.366742
2021-03-31           NaN  3055.0  3366.0  3047.0   9468.0      0.355513
2021-04-01           NaN  2637.0  3011.0  2863.0   8511.0      0.353777
2021-04-02           NaN   739.0  1039.0   854.0   2632.0      0.394757
2021-04-03           NaN  1530.0  1499.0  1014.0   4043.0      0.370764
2021-04-04           NaN   606.0   760.0   552.0   1918.0      0.396246
2021-04-05           NaN  2444.0  3809.0  3401.0   9654.0      0.394551
2021-04-06           NaN  2286.0  3154.0  2931.0   8371.0      0.376777
2021-04-07           NaN  2451.0  3084.0  2715.0   8250.0      0.373818
2021-04-08           NaN  2408.0  3221.0  2757.0   8386.0      0.384093
2021-04-09           NaN  2244.0  2868.0  2370.0   7482.0      0.383320
2021-04-10           NaN  1386.0  1388.0   917.0   3691.0      0.376050
2021-04-11           NaN   669.0   774.0   384.0   1827.0      0.423645
2021-04-12           NaN  2363.0  2829.0  1786.0   6978.0      0.405417
2021-04-13           NaN  2590.0  2200.0  1032.0   5822.0      0.377877
2021-04-14           NaN  1983.0  1545.0   596.0   4124.0      0.374636
2021-04-15           NaN   696.0   660.0   262.0   1618.0      0.407911